version: 2.1

jobs:

  Save-hello-world:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print-hello-world:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  

workflows:
  say-hello-workflow:
    jobs:
      - Save-hello-world
      - print-hello-world:
          requires:
            - Save-hello-world
