version: 2.1

jobs:

  print-hello:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, "

  print-world:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo World!"

  print-name:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run:
          name: "Say My Name"
          command: "echo Hello $MY_ENV_VAR!"

workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-name:
          requires:
            - print-hello
            - print-world